name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: Self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json  # Specify the path to package-lock.json
    - name: Install dependencies
      run: |
        cd backend
        npm ci
    - name: Create .env file
      run: |
        cd backend
        touch .env
        echo "Hello World" > .env
