name: Hello World Workflow

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  hello-world-job:
    runs-on: Self-hosted

    steps:
      # Step 1: Checkout the repository
      - name: Check out the repository
        uses: actions/checkout@v3

      # Step 2: Print "Hello World" to the console
      - name: Print Hello World
        run: echo "Hello World"

      - name: Run inline shell script
        run: |
          echo "Hello from the inline shell script!"
          echo "Listing files in the current directory:" > /home/ashwini/asheini.txt
                  
